package nl.codefox.bastion.util;

import net.dv8tion.jda.core.EmbedBuilder;
import net.dv8tion.jda.core.entities.MessageEmbed;

import java.awt.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.TimeZone;

/**
 * @author Joshua Slik
 */
public class BotEmbedBuilder extends EmbedBuilder {

	private long startTime;

	public BotEmbedBuilder() {
		this.startTime = System.currentTimeMillis();
		this.setColor(new Color(0, 255, 0));
	}

	@Override
	public MessageEmbed build() {
		Date date = new Date();
		DateFormat df = new SimpleDateFormat("EEE MMM dd'rd', yyyy 'at' HH:mm zzz");
		df.setTimeZone(TimeZone.getTimeZone("UTC"));

		// TODO Dymanic version
		String footerBuilder = String.format("This was generated by B4ST10N %s", "0.1.0" +
				" | " +
				df.format(date) +
				" | " +
				String.valueOf(System.currentTimeMillis() - startTime) + " ms");

		this.setFooter(footerBuilder, null);
		return super.build();
	}

}